- name: Install Docker + Vector to all nodes
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common

- name: Install Grafana + VictoriaMetrics on central node
  hosts: main_node
  become: true
  roles:
    - grafana_vm


- name: Install VM_agent
  hosts: vmagent_nodes
  become: true
  roles:
    - vm_agent