- name: Install Docker + Vector to all nodes
  hosts: vps
  gather_facts: true
  roles:
    - common
    - vector

- name: Install Grafana + VictoriaMetrics on central node
  hosts: main_node
  roles:
    - grafana_vm


- name: Install VM_agent
  hosts: vmagent_nodes
  roles:
    - vm_agent