- name: Create project directory
  file:
    path: /opt/vector
    state: directory

- name: Upload vector.toml
  ansible.builtin.template:
    src: ./templates/vector.toml.j2
    dest: /opt/vector/vector.toml
    mode: '0644'

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/vector/docker-compose.yml
    mode: '0644'

#- name: Copy .env
#  copy:
#    src: .env
#    dest: /opt/vector/.env
#    mode: '0600'

- name: Launch Vector
  shell: docker compose up -d
  args:
    chdir: /opt/vector
