services:
  vector:
    image: timberio/vector:nightly-debian
    container_name: vector
    ports:
      - 8686:8686
      - 9598:9598
    volumes:
      - ./vector.toml:/opt/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
    environment:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /host/etc
    command: ["--config", "/opt/vector/vector.toml"]
    restart: always
    
