# Configuration file version
apiVersion: 1

# List of data sources to insert/update
datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true


