- name: set GF_DIR
  ansible.builtin.set_fact:
    GF_DIR: /opt/grafana_vm

- name: Create project directory
  file:
    path: "{{ GF_DIR }}"
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{ GF_DIR }}/docker-compose.yml"
    mode: '0644'

- name: Ensure group 'grafana' exists
  ansible.builtin.group:
    name: grafana
    state: present

# - name: Add the user 'grafana' to the group 'grafana'
#   user:
#     name: grafana
#     shell: /sbin/nologin
#     groups: grafana
#     append: yes
    
- name: Copy .env
  copy:
    src: .env
    dest: "{{ GF_DIR }}/.env"
    mode: '0600'
    
- name: Read GF_SECURITY_ADMIN_USER from .env
  shell: dotenvx get -f .env | jq .GF_SECURITY_ADMIN_USER
  args:
    chdir: "{{ GF_DIR }}"
  register: GF_SECURITY_ADMIN_USER

- name: Read GF_SECURITY_ADMIN_PASSWORD from .env
  shell: dotenvx get -f .env | jq .GF_SECURITY_ADMIN_PASSWORD
  args:
    chdir: "{{ GF_DIR }}"
  register: GF_SECURITY_ADMIN_PASSWORD

- name: Make grafana.key
  shell: dotenvx get GF_SSL_PK > "{{ GF_DIR }}/grafana.key"
  args:
    chdir: "{{ GF_DIR }}"
#  register: GF_SSL_PK

- name: Copy .grafana.crt
  copy:
    src: ./ssl/grafana.crt
    dest: "{{ GF_DIR }}/grafana.crt"
    mode: '0644'

- name: Copy grafana.ini
  copy:
    src: ./files/grafana.ini
    dest: "{{ GF_DIR }}/grafana.ini"
    mode: '0644'

- name: Change ownership
  ansible.builtin.file:
    path: "{{ GF_DIR }}/grafana.ini"
    state: file
    owner: grafana
    mode: '0644'

- name: Change ownership
  ansible.builtin.file:
    path: "{{ GF_DIR }}/grafana.key"
    state: file
    owner: grafana
    group: grafana
    mode: '0400'

- name: Change ownership
  ansible.builtin.file:
    path: "{{ GF_DIR }}/grafana.crt"
    state: file
    owner: grafana
    group: grafana
    mode: '0400'

- name: Copy victoria_metrics.yml
  copy:
    src: ./provisioning/datasources/victoria_metrics.yml
    dest: "{{ GF_DIR }}/victoria_metrics.yml"
    mode: '0644'

- name: Launch stack
  shell: docker compose up -d
  args:
    chdir: "{{ GF_DIR }}"