- name: Create project directory
  file:
    path: /opt/grafana_vm
    state: directory


- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/grafana_vm/docker-compose.yml
    mode: '0644'
    
- name: Copy victoria_metrics.yml
  copy:
    src: ./provisioning/datasources/victoria_metrics.yml
    dest: /opt/grafana_vm/victoria_metrics.yml
    mode: '0644'

- name: Copy .env
  copy:
    src: .env
    dest: /opt/grafana_vm/.env
    mode: '0600'
    

- name: Launch stack
  shell: docker compose up -d
  args:
    chdir: /opt/grafana_vm
