services:
  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: vm_agent
    ports:
      - '8429:8429'
    volumes:
      - 'vmagent_data:/vmagent_data'
      - "./promscrape.yml:${VM_AGENT_DIR}/promscrape.yml:ro"
      - "./files/targets_cadvisor.json:${VM_AGENT_DIR}/targets_cadvisor.json:ro"
      - "./files/targets_host-metrics.json:${VM_AGENT_DIR}/targets_host-metrics.json:ro"
    command:
      - "-promscrape.config=${VM_AGENT_DIR}/promscrape.yml"
      - '-remoteWrite.url=${VM_REMOTEWRITE_URL}'
    restart: always
    extra_hosts:
      - "ru:${RU_VPS_IP}"
      - "kz:${KZ_VPS_IP}"
      - "eu:${EU_VPS_IP}"
      
      
volumes:
  vmagent_data: {}