services:
  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: vm_agent
    ports:
      - '8429:8429'
    volumes:
      - 'vmagent_data:/vmagent_data'
      - "./files/targets_cadvisor.json:/opt/vm_agent/targets_cadvisor.json:ro"
      - "./files/targets_host-metrics.json:/opt/vm_agent/targets_host-metrics.json:ro"
      - "./promscrape.yml:/opt/vm_agent/promscrape.yml:ro"
    command:
      - "-promscrape.config=/opt/vm_agent/promscrape.yml"
      - '-remoteWrite.url=http://217.171.146.251:8428/api/v1/write'
    restart: always
    extra_hosts:
      { "ru": "217.171.146.251", "kz": "38.180.207.69", "eu": "51.38.152.67" }
      
      
volumes:
  vmagent_data: {}