services:
  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: vm_agent
    ports:
      - '8429:8429'
    volumes:
      - 'vmagent_data:/vmagent_data'
      - './cadvisor.json:/cadvisor.json'
      - './host-metrics.json:/host-metrics.json'
      - './promscrape.yml:/promscrape.yml'
    command:
      - '-promscrape.config=promscrape.yml'
      - '-remoteWrite.url=http://ru:8428/api/v1/write'
      - '-promscrape.fileSDCheckInterval=30s'
    restart: always
    extra_hosts:
      { "ru": "217.171.146.251", "kz": "38.180.207.69", "eu": "51.38.152.67" }
      
      
volumes:
  vmagent_data: {}