
- name: Create project directory
  file:
    path: $VM_AGENT_DIR
    state: directory

- name: Upload promscrape.yml
  ansible.builtin.template:
    src: ./templates/promscrape.yml.j2
    dest: $VM_AGENT_DIR/promscrape.yml
    mode: '0644'
    
- name: Upload host_metrics_targets.json
  ansible.builtin.template:
    src: ./templates/host_metrics_targets.json.j2
    dest: $VM_AGENT_DIR/host_metrics_targets.json
    mode: '0644'  

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: $VM_AGENT_DIR/docker-compose.yml
    mode: '0644'    
    
- name: Copy .env
  copy:
    src: .env
    dest: $VM_AGENT_DIR.env
    mode: '0600'

- name: Encrypt .env
  shell: |
    dotenvx run -f .env -- python3 index.py
    dotenvx set HELLO "public (enc)" -f .env
    
- name: Launch vm_agent
  shell: docker compose up -d
  args:
    chdir: $VM_AGENT_DIR
    env:
      GF_SECURITY_ADMIN_USER=echo 'import os;print(os.getenv("GF_SECURITY_ADMIN_USER, ""))' > index.py'
      GF_SECURITY_ADMIN_PASSWORD=echo 'import os;print(os.getenv("GF_SECURITY_ADMIN_PASSWORD, ""))' > index.py'
      GF_DIR=/opt/grafana