- name: set VM_AGENT_DIR
  ansible.builtin.set_fact:
    VM_AGENT_DIR: /opt/vm_agent

- name: Create project directory
  file:
    path: "{{ VM_AGENT_DIR }}"
    state: directory
    
- name: Copy targets_host-metrics.json
  copy:
    src: ./files/targets_host-metrics.json
    dest: "{{ VM_AGENT_DIR }}/targets_host-metrics.json"
    mode: '0600'

- name: Copy targets_host-metrics.json
  copy:
    src: "./files/targets_cadvisor.json"
    dest: "{{ VM_AGENT_DIR }}/targets_cadvisor.json"
    mode: '0600'

- name: Upload promscrape.yml
  ansible.builtin.template:
    src: ./templates/promscrape.yml.j2
    dest: "{{ VM_AGENT_DIR }}/promscrape.yml"
    mode: '0644'

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{ VM_AGENT_DIR }}/docker-compose.yml"
    mode: '0644'    
    
- name: Copy .env
  copy:
    src: .env
    dest: "{{ VM_AGENT_DIR }}/.env"
    mode: '0600'

- name: Launch vm_agent
  command: docker compose up -d
  args:
    chdir: "{{ VM_AGENT_DIR }}"
    