- name: Upload vector.toml
  ansible.builtin.template:
    src: ./templates/vector.toml.j2
    dest: vector.toml
    mode: '0644'

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: docker-compose.yml
    mode: '0644'

- name: Launch stack
  shell: |
    docker compose up -d
    docker compose restart