- name: Import nginx install task
  import_tasks: install_docker.yml

- name: Import apache install task
  import_tasks: tasks/install_dotenvx.yml

- name: Import apache install task
  import_tasks: tasks/vector.yml