- name: Docker install task
  import_tasks: tasks/install_docker.yml

- name: Dotenvx install task
  import_tasks: tasks/install_dotenvx.yml

- name: Vector install task
  import_tasks: tasks/vector.yml