- name: Install Docker dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG key
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Install Docker engine and compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Install Dotenvx
  shell: curl -sfS https://dotenvx.sh/install.sh | sh
  args:
    creates: /usr/local/bin/dotenvx

- name: Define var <host_ipv4>
  debug: msg={{ hostvars[inventory_hostname][ansible_default_ipv4][address] }}

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: docker-compose.yml
    mode: '0644'

- name: Launch stack
  shell: docker compose up -d
