- name: Docker install task
  include_tasks: ./common/tasks/install_docker.yml

- name: Dotenvx install task
  include_tasks: ./common/tasks/install_dotenvx.yml

- name: Vector install task
  include_tasks: ./common/tasks/vector.yml