- name: Complete common import_tasks
  import_tasks: 'tasks/install_*.yml'
  args:
    chdir: "/roles/common"



# - name: Complete common tasks
#   ansible.builtin.include_tasks:
#     file: [ tasks/install_docker.yml, tasks/install_dotenvx.yml, tasks/install_vector.yml ]
#   args:
#     chdir: "/roles/common"