name: CI
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOSTS_JSON: ${{ vars.HOSTS_JSON }}

    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Generate inventory-dev.yml
        run: |
          ru_ip=$(echo "$HOSTS_JSON" | jq -r .ru)
          kz_ip=$(echo "$HOSTS_JSON" | jq -r .kz)
          eu_ip=$(echo "$HOSTS_JSON" | jq -r .eu)
          
          cat <<EOF > inventory-dev.yml
    
all:
  hosts:
    ru:
      ansible_host: $ru_ip
    kz:
      ansible_host: $kz_ip
    eu:
      ansible_host: $eu_ip EOF

          

      - name: Add SSH key
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY }}" | tr -d "\r" | ssh-add -


      - name: Run playbook
        run: |
          cat inventory-dev.yml
          ansible-playbook -i inventory-dev.yml playbook.yml -e "HOSTS_JSON=some_value"
          eval "${(ssh-agent -k)}"
