name: CI
on:
  push:

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: R1ckySpanish/ansible
    steps:
    
      - name: run deploy
        run: ansible-playbook -i inventory.yml all --private-key $SSH_KEY playbook.yml -b
