# python
name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: curl -sfS https://dotenvx.sh/install.sh | sh
      env:
        DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible


      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/ansible.key
          chmod 600 ~/.ssh/ansible.key
          

      - name: Add SSH key
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY }}" | tr -d "\r" | ssh-add -


      - name: Run playbook
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          env
          ls -la */*/*
          sudo find / -iname "*playbook.yml"
          ls -l playbook.yml
          ansible-playbook -i inventory.yml playbook.yml
          eval "$(ssh-agent -k)"

