name: ci-pipeline
on: push
env:
  DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
  ANSIBLE_HOST_KEY_CHECKING: 'False'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run playbook
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_KEY }}" | tr -d "\r" | ssh-add -
        ansible-playbook -i inventory.yml playbook.yml -v
        eval "$(ssh-agent -k)"