name: ci-pipeline
on: 
  push
env:
  DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
    
    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
        ANSIBLE_CONFIG: '/etc/ansible/ansible.cfg'
      run: |
        touch $ANSIBLE_CONFIG; echo -e "[defaults]  \nask_become_pass = false" > $ANSIBLE_CONFIG
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_KEY }}" | tr -d "\r" | ssh-add -
        ansible-playbook -i inventory.yml playbook.yml -vvv
        eval "$(ssh-agent -k)"