name: CI
on:


jobs:
  deploy:
    runs-on: [self-hosted, linux, kz]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/ansible.key
          chmod 600 ~/.ssh/ansible.key
          

      - name: Add SSH key
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY }}" | tr -d "\r" | ssh-add -


      - name: Run playbook
        run: |
          ansible-playbook -i inventory.yml --limit vm_agent playbook.yml -b --key-file ~/.ssh/ansible.key
          eval "$(ssh-agent -k)"
